apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
      - name: api
        image: nafizimtiaz/weather_api:2508041411
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
          - name: WEATHER_API_KEY
            valueFrom:
              secretKeyRef:
                name: weather-secret
                key: key
        ports:
          - containerPort: 8000
